server.port: 3001
spring:
  ############## kafka (Spring Cloud Stream)
  cloud:
    stream:
      kafka:
        binder:
          autoCreateTopics: false
          autoAddPartitions: false
          # zookeeper server address
          zkNodes: localhost:2156
          # kafka server address
          brokers: localhost:9091
      bindings:
        output:
          # topic-name
          destination:
        input:
          # topic-name
          destination:
  ############## datasource ##############
  datasource:
    url: jdbc:mariadb://localhost:3306/demo_service?characterEncoding=UTF-8
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: osckorea!
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
